PE/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.decorators import login_required

from django.contrib.auth import views
from PEapp.views import PrescriptionDetailView, MedicalRecordDetailView,home, signup,create_approval, approve_approval
from PEapp.admin import LoginForm, UserCreationForm
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('login/', auth_views.login, {'template_name': 'login.html', 'authentication_form': LoginForm}, name='login'),
    path('logout/', auth_views.logout, {'next_page': '/'}, name='logout'),
    path('signup/', signup, name='signup'),
    path('prescription/<int:pk>', login_required(PrescriptionDetailView.as_view()), name='prescription-detail'),
    path('medicalrecord/<int:id>', login_required(MedicalRecordDetailView.as_view()), name='medicalrecord-detail'),
    path('create_approval/', create_approval, name='create_approval'),
    path('approve_approval/', approve_approval, name='approve_approval'),

]

PEapp/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)

class MyUserManager(BaseUserManager):
    def create_user(self, user_name, email, name, user_type, date_of_birth=None, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not user_name:
            raise ValueError('Users must have an user name')

        user = self.model(
            email=self.normalize_email(email),
            user_name = user_name,
            date_of_birth=date_of_birth,
            name=name,
            user_type=user_type
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, user_name, email, name, password, **args):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(user_name, email, name,'O',password = password)
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    name = models.CharField(
        verbose_name='full name',
        max_length=255
    )
    user_name = models.CharField(
        verbose_name='user name',
        max_length=255,
        unique=True,
    )
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    USER_TYPES = (
        ('P', 'Patient'),
        ('D', 'Doctor'),
        ('C', 'Pharmacist'),
        ('O', 'Other')
    )
    user_type = models.CharField(
        verbose_name='user type',
        max_length=1,
        default='P',
        choices=USER_TYPES
    )
    date_of_birth = models.DateField(null=True, blank=True)

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'user_name'
    REQUIRED_FIELDS = ['name', 'email']

    class Meta:
        ordering = ["name"]
        verbose_name = 'User'

    def __str__(self):
        return self.user_name

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True




class Prescription(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(to=MyUser,related_name='prescription_user',on_delete=models.DO_NOTHING)
    content = models.TextField()

    class Meta:
        permissions = (
            ('view_task', 'View task'),
        )

    def __str__(self):
        return self.user.email

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('prescription-detail', args=[str(self.id)])

class MedicalRecord(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(to=MyUser,related_name='medicalrecord_user',on_delete=models.DO_NOTHING,)
    content = models.TextField()

    class Meta:
        permissions = (
            ('view_task', 'View task'),
        )

    def __str__(self):
        return self.user.email

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('medicalrecord-detail', args=[str(self.id)])


class Approval(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    prescription_no = models.ForeignKey(to=Prescription,on_delete=models.DO_NOTHING,)

    requester = models.ForeignKey(to=MyUser,on_delete=models.DO_NOTHING,)
    # approver = models.ForeignKey(to=MyUser,on_delete=models.DO_NOTHING,)

    STATUS_TYPES = (
        ('PE', 'Pending'),
        ('AP', 'Approved')
    )
    status = models.CharField(
        max_length=2,
        default='PE',
        choices=STATUS_TYPES
    )

    def __str__(self):
        return self.requester.email

PEapp/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render,redirect
from django.urls import reverse
from django.views.generic.detail import DetailView
from django.utils import timezone

from PEapp.models import Prescription, MedicalRecord, MyUser,Approval
from PEapp.admin import UserCreationForm
from django.contrib.auth import login, authenticate

# Create your views here.

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('user_name')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('home')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})

@login_required(login_url="login/")
def home(request):
    context = {}
    if request.user.user_type == "P":
        context["pending_approvals"] = Approval.objects.filter(status="PE", prescription_no__user=request.user)
    else:
        context["approved_prescriptions"] = Prescription.objects.filter(approval__requester=request.user,approval__status="AP")
        context["pending_prescriptions"] = Prescription.objects.filter(approval__requester=request.user,approval__status="PE")
        context["available_prescriptions"] = Prescription.objects.filter(Q(approval__isnull=True)) | Prescription.objects.filter(~Q(approval__requester=request.user))
    return render(request, context=context, template_name="index.html")


# @login_required(login_url="login/")
class PrescriptionDetailView(DetailView):
    model = Prescription
    template_name = 'prescription.html'

    def get_context_data(self, **kwargs):
        context = super(PrescriptionDetailView, self).get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context


class MedicalRecordDetailView(DetailView):
    model = MedicalRecord
    template_name = 'medical_rec.html'

    def get_context_data(self, **kwargs):
        context = super(MedicalRecordDetailView, self).get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context


@login_required(login_url="login/")
def create_approval(request):
    user_id = request.POST['user']
    requester = MyUser.objects.get(id=user_id)
    prescription_id = request.POST['prescription']
    prescription = Prescription.objects.get(id=prescription_id)
    Approval.objects.create(requester=requester, prescription_no=prescription)
    return HttpResponseRedirect(reverse('home'))


@login_required(login_url="login/")
def approve_approval(request):
    approval_id = request.POST['approval_id']
    approval = Approval.objects.get(id = approval_id)
    user_id = request.POST['user']
    user = MyUser.objects.get(id=user_id)
    if approval.prescription_no.user.user_name == user.user_name:
        approval.status = 'AP'
        approval.save()
    return HttpResponseRedirect(reverse('home'))

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.1/css/materialize.min.css">
    <style media="screen" type="text/css">
        body {
            display: flex;
            min-height: 100vh;
            flex-direction: column;
        }
        main {
            flex: 1 0 auto;
        }
    </style>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.1/js/materialize.min.js"></script>
    <script type="text/javascript">
        jQuery(document).ready(function ($) {
            $('select').material_select();
            $(".dropdown-button").dropdown();
        });
    </script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta charset="UTF-8">
    <title>Kapish</title>
</head>
<body>
<header>
    {% block header %}{% endblock %}
</header>
<main>
    <br>
    {% block body %}{% endblock %}
</main>
<footer class="page-footer teal" style="!important;padding-top: 0">
    <div class="footer-copyright">
        <div class="container">© 2018 Copyright Kapish
            <a class="grey-text text-lighten-4 right" href="/admin">Django Admin</a></div>
    </div>
</footer>
</body>
</html>

templates/header.html
<nav>
    <div class="nav-wrapper teal">
        <a href="/" class="brand-logo center">PharmEasy</a>

        <ul class="right hide-on-med-and-down">
        {% if user.is_authenticated %}
            <li> Welcome {{ user }} </li>
            <li><a href="/logout">Logout</a></li>
        {% else %}
            <li><a href="/login">Login</a></li>
            <li><a href="/signup">SignUp</a></li>
        {% endif %}
        </ul>
    </div>
</nav>

templates/index.html
{% extends 'base.html' %}
{% block header %}
    {% include 'header.html' %}
{% endblock %}

{% block body %}
    <div class="row">
        {% if user.user_type == 'P' %}
            <div class="col s12 m8 offset-m2">
                <h4>Pending Approvals</h4>
                {% for approval in pending_approvals %}
                    <div class="card">
                        <div class="card-content">
                            <span class="card-title grey-text text-darken-4">{{ forloop.counter }}) {{ approval.requester.get_user_type_display }} {{ approval.requester.name }} </span>
                            <p><strong> {{ approval.requester.get_user_type_display }} {{ approval.requester.name }} </strong> has asked for your Approval to view your Prescription Dated: {{ approval.prescription_no.created_at|date:"SHORT_DATE_FORMAT" }}.
                                If you want him to view your Prescription chose Approve</p>
                        </div>
                        <div class="card-action">
                            <form action="{% url 'approve_approval' %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="user" value="{{ user.id}}">
                                <input type="hidden" name="approval_id" value="{{ approval.id}}">
                                <button class="btn waves-effect waves-light" type="submit" style="float: right;margin-bottom: 10px;margin-right: 10px;">Approve
                                    <i class="material-icons right">send</i>
                                </button>
                            </form>
                        </div>
                    </div>
                {% empty %}
                    <li>Sorry, no prescriptions available.</li>
                {% endfor %}
            </div>

        {% else %}
            <div class="col s12 m8 offset-m2">
                {% if approved_prescriptions  %}
                    <h4>Approved Patient Prescriptions</h4>
                {% endif %}
                {% for prescription in approved_prescriptions %}
                    <div class="card">
                        <div class="card-content">
                            <span class="card-title grey-text text-darken-4">{{ forloop.counter }}) Patient name: {{ prescription.user.name }}, Date: {{ prescription.created_at|date:"SHORT_DATE_FORMAT" }}</span>
                            <p><strong> Patient {{ prescription.user.name }}</strong> has approved your request to view his Prescription</p>
                        </div>
                        <div class="card-action">
                            <form action="{{ prescription.get_absolute_url }}">
                                <button class="btn waves-effect waves-light"  style="float: right;margin-bottom: 10px;margin-right: 10px;">See Prescription
                                    <i class="material-icons right">send</i>
                                </button>
                            </form>
                        </div>
                    </div>
                {% endfor %}

                {% if available_prescriptions  %}
                    <h4>Available Prescriptions - Needs Approval</h4>
                {% endif %}
                {% for prescription in available_prescriptions %}
                    <div class="card">
                        <div class="card-content">
                            <span class="card-title grey-text text-darken-4">{{ forloop.counter }}) Patient name: {{ prescription.user.name }}, Date: {{ prescription.created_at|date:"SHORT_DATE_FORMAT" }}</span>
                            {#                            <p><strong> Patient {{ prescription.user.name }}</strong> has approved your request to view his Prescription</p>#}
                        </div>
                        <div class="card-action">
                            <form action="{% url 'create_approval' %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="user" value="{{ user.id}}">
                                <input type="hidden" name="prescription" value="{{ prescription.id }}">
                                <button class="btn waves-effect waves-light" type="submit" style="float: right;margin-bottom: 10px;margin-right: 10px;">Ask For Approval
                                    <i class="material-icons right">send</i>
                                </button>
                            </form>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block header %}
    {% include 'header.html' %}
{% endblock %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col s6 offset-s3 z-depth-1" id="panell" style="margin-top: 70px;padding: 0px;">
            <h5 id="title" style="background-color: #009688;color: white;padding: 8px;margin-top: 0px">Login Form</h5>
            <form method="post" action="{% url 'login' %} " style="padding:0px;border-radius: 3px;box-sizing: border-box;">
                {% csrf_token %}
                {{ form }}
            <button class="btn waves-effect waves-light" type="submit" style="float: right;margin-bottom: 10px;margin-right: 10px;">Login
                    <i class="material-icons right">send</i>
            </button>
        </form>
            <br>
        </div>
      </div>

    </div>
{% endblock body %}

templates/medical_rec.html
{% extends 'base.html' %}
{% block header %}
    {% include 'header.html' %}
{% endblock %}

{% block body %}

<div class="container">

</div>
{% endblock body %}

templates/prescription.html
{% extends 'base.html' %}
{% block header %}
    {% include 'header.html' %}
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col s12 m8 offset-m2">
            <div class="card">
                <div class="card-content">
                    <span class="card-title grey-text text-darken-4">Patient: {{ object.user.name }},  Date: {{ object.created_at|date:"SHORT_DATE_FORMAT" }}</span>
                    <p>{{ object.content }}</p>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}

templates/signup.html
{% extends 'base.html' %}
{% block header %}
    {% include 'header.html' %}
{% endblock %}}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col s6 offset-s3 z-depth-1" id="panell" style="margin-top: 60px;padding: 0px;">
            <h5 id="title" style="background-color: #009688;color: white;padding: 8px;margin-top: 0px">SignUp</h5>
            <form method="post" action="{% url 'signup' %}" style="padding:0px;border-radius: 3px;box-sizing: border-box;">
                {% csrf_token %}

                {{ form }}
            <button class="btn waves-effect waves-light" type="submit" style="float: right;margin-bottom: 10px;margin-right: 10px;">Signup
                    <i class="material-icons right">send</i>
            </button>
            </form>
            <br>
        </div>
      </div>

    </div>
{% endblock body %}